### ISSUE TITLE
Terms with more than one `population:size` annotation not related to it

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#20]
Complete list of terms with more than one `population:size`. Values are separated with |
Related to #18 

entity | value
-- | --
http://purl.obolibrary.org/obo/AfPO_0000358 | Nilo-Saharan, Eastern Sudanic\|1.7 million
http://purl.obolibrary.org/obo/AfPO_0000414 | 0.1 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Northwest\|A
http://purl.obolibrary.org/obo/AfPO_0000414 | 0.1 million\|Niger–Congo
http://purl.obolibrary.org/obo/AfPO_0000075 | 0.3 million\|Nilo-Saharan\|Satellite-Core\|Core\|Eastern\|Sudanic	Southern\|Nilotic\|Southern
http://purl.obolibrary.org/obo/AfPO_0000407 | Niger–Congo, Bantu\|1.4 million
http://purl.obolibrary.org/obo/AfPO_0000407 | 1.4 million\|Niger–Congo, Bantu
http://purl.obolibrary.org/obo/AfPO_0000437 | 16 millions\|Niger–Congo, Bantu
http://purl.obolibrary.org/obo/AfPO_0000329 | Indo-European\|0.03 millions
http://purl.obolibrary.org/obo/AfPO_0000220 | 0.57 million\|Afro-Asiatic\|Semitic\|Central\|South\|Arabic\|Mandaic\|Northwestern\|West
http://purl.obolibrary.org/obo/AfPO_0000397 | Afro-Asiatic\|Semitic\|South\|Ethiopian\|North\|Mandaic\|Northwestern\|West\|1.5 millions
http://purl.obolibrary.org/obo/AfPO_0000386 | 0.2 million\|Afro-Asiatic, Cushitic
http://purl.obolibrary.org/obo/AfPO_0000414 | Niger–Congo\|0.1 million
http://purl.obolibrary.org/obo/AfPO_0000414 | Niger–Congo\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Northwest\|A
http://purl.obolibrary.org/obo/AfPO_0000388 | Afro-Asiatic\|Cushitic\|East\|Highland\|>3 millions
http://purl.obolibrary.org/obo/AfPO_0000295 | 0.018 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Wide Grassfields\|Narrow Grassfields\|Momo\|Nun
http://purl.obolibrary.org/obo/AfPO_0000414 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Northwest\|A\|0.1 million
http://purl.obolibrary.org/obo/AfPO_0000414 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Northwest\|A\|Niger–Congo
http://purl.obolibrary.org/obo/AfPO_0000121 | 0.74 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Senufo\|Suppire-Mamara\|Kirma-Tyurama\|Western\|Southeast\|Dagaari-Birifor\|Dagaari
http://purl.obolibrary.org/obo/AfPO_0000386 | Afro-Asiatic, Cushitic\|0.2 million
http://purl.obolibrary.org/obo/AfPO_0000338 | 0.05 million\|Niger–Congo, Bantu
http://purl.obolibrary.org/obo/AfPO_0000126 | 3 millions\|Nilo-Saharan\|Satellite-Core\|Core\|Eastern Sudanic\|Southern\|Nilotic\|Western\|Dinka-Nuer
http://purl.obolibrary.org/obo/AfPO_0000420 | Niger–Congo, Volta-Niger\|1.5 millions
http://purl.obolibrary.org/obo/AfPO_0000058 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Tivoid\|3.8 millions
http://purl.obolibrary.org/obo/AfPO_0000391 | 24 millions\|Afro-Asiatic\|Semitic\|South\|Ethiopian\|South\|Transversal\|Amharic-Argobba\|West
http://purl.obolibrary.org/obo/AfPO_0000191 | 0.050 million\|Nilo-Saharan\|Satellite-Core\|Core\|Eastern Sudanic\|Northern\|Nubian\|Central
http://purl.obolibrary.org/obo/AfPO_0000351 | 2.3 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S
http://purl.obolibrary.org/obo/AfPO_0000421 | 6 millions\|Niger–Congo, Gbe
http://purl.obolibrary.org/obo/AfPO_0000387 | Afro-Asiatic\|Cushitic\|East\|Saho-Afar\|0.2 million
http://purl.obolibrary.org/obo/AfPO_0000351 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S\|2.3 millions
http://purl.obolibrary.org/obo/AfPO_0000378 | 2.2 millions\|Nilo-Saharan, Nilotic, Luo
http://purl.obolibrary.org/obo/AfPO_0000345 | 1 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S
http://purl.obolibrary.org/obo/AfPO_0000434 | >5 millions\|Nilo-Saharan\|Songhai\|Southern\|Maban\|Surbakhal\|Kresh\|Sinyar\|Sara\|Vale\|Sara Kaba\|Luo\|Lango-Acholi
http://purl.obolibrary.org/obo/AfPO_0000419 | 0.3 millions\|Niger–Congo, Cross River
http://purl.obolibrary.org/obo/AfPO_0000366 | Afro-Asiatic, Semitic\|2 millions
http://purl.obolibrary.org/obo/AfPO_0000416 | 1.591 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Dogon\|Unclassified\|Western\|Southwestern\|B\|North-South\|Ubaghara-Kohumono\|Ubaghara
http://purl.obolibrary.org/obo/AfPO_0000113 | 40 millions\|Afro-Asiatic\|Cushitic\|East\|Oromo
http://purl.obolibrary.org/obo/AfPO_0000224 | 0.250 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Jarawan\|Nigerian
http://purl.obolibrary.org/obo/AfPO_0000066 | 0.026 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E
http://purl.obolibrary.org/obo/AfPO_0000113 | Afro-Asiatic\|Cushitic\|East\|Oromo\|40 millions
http://purl.obolibrary.org/obo/AfPO_0000372 | 2 millions\|Afro-Asiatic\|Omotic\|North\|Gonga-Gimojan\|Gimojan\|Ometo-Gimira\|Ometo\|Central
http://purl.obolibrary.org/obo/AfPO_0000346 | 0.3 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|R
http://purl.obolibrary.org/obo/AfPO_0000399 | 0.06 million\|Language Isolate
http://purl.obolibrary.org/obo/AfPO_0000398 | Pygmy\|Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|West\|Bongo-Bagirmi\|Bongo-Baka\|Baka\|Kacipo-Balesi\|Tennet\|Luo\|Lango-Acholi
http://purl.obolibrary.org/obo/AfPO_0000398 | Pygmy\|0.25 million
http://purl.obolibrary.org/obo/AfPO_0000434 | Nilo-Saharan\|Songhai\|Southern\|Maban\|Surbakhal\|Kresh\|Sinyar\|Sara\|Vale\|Sara Kaba\|Luo\|Lango-Acholi\|>5 millions
http://purl.obolibrary.org/obo/AfPO_0000075 | Nilo-Saharan\|Satellite-Core\|Core\|Eastern\|Sudanic	Southern\|Nilotic\|Southern\|0.3 million
http://purl.obolibrary.org/obo/AfPO_0000085 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E\|0.34 millions
http://purl.obolibrary.org/obo/AfPO_0000410 | 0.05 million\|Niger–Congo, Gbe
http://purl.obolibrary.org/obo/AfPO_0000435 | Niger–Congo\|0.2 million
http://purl.obolibrary.org/obo/AfPO_0000325 | Indo-European\|2.8–3.5 million
http://purl.obolibrary.org/obo/AfPO_0000191 | Nilo-Saharan\|Satellite-Core\|Core\|Eastern Sudanic\|Northern\|Nubian\|Central\|0.050 million
http://purl.obolibrary.org/obo/AfPO_0000366 | 2 millions\|Afro-Asiatic, Semitic
http://purl.obolibrary.org/obo/AfPO_0000328 | 4.7 millions\|Indo-European
http://purl.obolibrary.org/obo/AfPO_0000390 | 11 millions\|Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|East\|Moru-Madi\|Central
http://purl.obolibrary.org/obo/AfPO_0000244 | Afro-Asiatic\|Cushitic\|South\|Yaaku\|B.3\|Zaar Proper\|0.030 million
http://purl.obolibrary.org/obo/AfPO_0000325 | 2.8–3.5 million\|Indo-European
http://purl.obolibrary.org/obo/AfPO_0000088 | 5.3 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E
http://purl.obolibrary.org/obo/AfPO_00003674 | Nilo-Saharan\|Satellite-Core\|Core\|B’aga\|0.2 million
http://purl.obolibrary.org/obo/AfPO_0000416 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Dogon\|Unclassified\|Western\|Southwestern\|B\|North-South\|Ubaghara-Kohumono\|Ubaghara\|1.591 millions
http://purl.obolibrary.org/obo/AfPO_0000420 | 1.5 millions\|Niger–Congo, Volta-Niger
http://purl.obolibrary.org/obo/AfPO_0000415 | Afro-Asiatic\|Chadic\|Biu-Mandara\|B\|B.1\|0.128 millions
http://purl.obolibrary.org/obo/AfPO_0000356 | Afro-Asiatic, Berber\|38 millions
http://purl.obolibrary.org/obo/AfPO_0000103 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S\|6 millions
http://purl.obolibrary.org/obo/AfPO_0000121 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Senufo\|Suppire-Mamara\|Kirma-Tyurama\|Western\|Southeast\|Dagaari-Birifor\|Dagaari\|0.74 million
http://purl.obolibrary.org/obo/AfPO_0000295 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Wide Grassfields\|Narrow Grassfields\|Momo\|Nun\|0.018 million
http://purl.obolibrary.org/obo/AfPO_0000126 | Nilo-Saharan\|Satellite-Core\|Core\|Eastern Sudanic\|Southern\|Nilotic\|Western\|Dinka-Nuer\|3 millions
http://purl.obolibrary.org/obo/AfPO_0000066 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E\|0.026 millions
http://purl.obolibrary.org/obo/AfPO_0000387 | 0.2 million\|Afro-Asiatic\|Cushitic\|East\|Saho-Afar
http://purl.obolibrary.org/obo/AfPO_0000340 | Niger–Congo, Bantu\|> 28 millions
http://purl.obolibrary.org/obo/AfPO_0000153 | 1 million\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Central\|Northern\|Oti-Volta\|Western\|Northwest\|Dagaari-Birifor\|Dagaari
http://purl.obolibrary.org/obo/AfPO_0000206 | Nilo-Saharan\|5 millions
http://purl.obolibrary.org/obo/AfPO_0000384 | 1 million\|Afro-Asiatic, Cushitic
http://purl.obolibrary.org/obo/AfPO_0000058 | 3.8 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Tivoid
http://purl.obolibrary.org/obo/AfPO_0000405 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|J\|5.4 millions
http://purl.obolibrary.org/obo/AfPO_0000398 | 0.25 million\|Pygmy
http://purl.obolibrary.org/obo/AfPO_0000398 | 0.25 million\|Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|West\|Bongo-Bagirmi\|Bongo-Baka\|Baka\|Kacipo-Balesi\|Tennet\|Luo\|Lango-Acholi
http://purl.obolibrary.org/obo/AfPO_0000435 | 0.2 million\|Niger–Congo
http://purl.obolibrary.org/obo/AfPO_0000328 | Indo-European\|4.7 millions
http://purl.obolibrary.org/obo/AfPO_0000365 | Afro-Asiatic, Semitic\|85 millions
http://purl.obolibrary.org/obo/AfPO_0000149 | 0.3 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Central\|Northern\|Oti-Volta\|Western\|Northwest
http://purl.obolibrary.org/obo/AfPO_0000388 | >3 millions\|Afro-Asiatic\|Cushitic\|East\|Highland
http://purl.obolibrary.org/obo/AfPO_0000358 | 1.7 million\|Nilo-Saharan, Eastern Sudanic
http://purl.obolibrary.org/obo/AfPO_0000224 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Jarawan\|Nigerian\|0.250 million
http://purl.obolibrary.org/obo/AfPO_0000419 | Niger–Congo, Cross River\|0.3 millions
http://purl.obolibrary.org/obo/AfPO_0000372 | Afro-Asiatic\|Omotic\|North\|Gonga-Gimojan\|Gimojan\|Ometo-Gimira\|Ometo\|Central\|2 millions
http://purl.obolibrary.org/obo/AfPO_0000190 | 1.7 million\|Nilo-Saharan, Eastern Sudanic
http://purl.obolibrary.org/obo/AfPO_0000085 | 0.34 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E
http://purl.obolibrary.org/obo/AfPO_0000405 | 5.4 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|J
http://purl.obolibrary.org/obo/AfPO_0000421 | Niger–Congo, Gbe\|6 millions
http://purl.obolibrary.org/obo/AfPO_0000411 | Creole, English based\|Atlantic\|Krio\|0.01 million
http://purl.obolibrary.org/obo/AfPO_0000384 | Afro-Asiatic, Cushitic\|1 million
http://purl.obolibrary.org/obo/AfPO_0000399 | Language Isolate\|0.06 million
http://purl.obolibrary.org/obo/AfPO_0000340 | > 28 millions\|Niger–Congo, Bantu
http://purl.obolibrary.org/obo/AfPO_0000411 | 0.01 million\|Creole, English based\|Atlantic\|Krio
http://purl.obolibrary.org/obo/AfPO_0000413 | Niger–Congo\|0.04
http://purl.obolibrary.org/obo/AfPO_0000365 | 85 millions\|Afro-Asiatic, Semitic
http://purl.obolibrary.org/obo/AfPO_00003674 | 0.2 million\|Nilo-Saharan\|Satellite-Core\|Core\|B’aga
http://purl.obolibrary.org/obo/AfPO_0000190 | Nilo-Saharan, Eastern Sudanic\|1.7 million
http://purl.obolibrary.org/obo/AfPO_0000410 | Niger–Congo, Gbe\|0.05 million
http://purl.obolibrary.org/obo/AfPO_0000244 | 0.030 million\|Afro-Asiatic\|Cushitic\|South\|Yaaku\|B.3\|Zaar Proper
http://purl.obolibrary.org/obo/AfPO_0000220 | Afro-Asiatic\|Semitic\|Central\|South\|Arabic\|Mandaic\|Northwestern\|West\|0.57 million
http://purl.obolibrary.org/obo/AfPO_0000392 | 1.9 millions\|Afro-Asiatic\|Semitic\|South\|Ethiopian\|South\|Outer\|tt-Group\|West
http://purl.obolibrary.org/obo/AfPO_0000338 | Niger–Congo, Bantu\|0.05 million
http://purl.obolibrary.org/obo/AfPO_0000391 | Afro-Asiatic\|Semitic\|South\|Ethiopian\|South\|Transversal\|Amharic-Argobba\|West\|24 millions
http://purl.obolibrary.org/obo/AfPO_0000225 | Language Isolate\|1300 persons
http://purl.obolibrary.org/obo/AfPO_0000345 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S\|1 million
http://purl.obolibrary.org/obo/AfPO_0000392 | Afro-Asiatic\|Semitic\|South\|Ethiopian\|South\|Outer\|tt-Group\|West\|1.9 millions
http://purl.obolibrary.org/obo/AfPO_0000225 | 1300 persons\|Language Isolate
http://purl.obolibrary.org/obo/AfPO_0000356 | 38 millions\|Afro-Asiatic, Berber
http://purl.obolibrary.org/obo/AfPO_0000378 | Nilo-Saharan, Nilotic, Luo\|2.2 millions
http://purl.obolibrary.org/obo/AfPO_0000397 | 1.5 millions\|Afro-Asiatic\|Semitic\|South\|Ethiopian\|North\|Mandaic\|Northwestern\|West
http://purl.obolibrary.org/obo/AfPO_0000206 | 5 millions\|Nilo-Saharan
http://purl.obolibrary.org/obo/AfPO_0000413 | 0.04\|Niger–Congo
http://purl.obolibrary.org/obo/AfPO_0000426 | 8.6 millions\|0.5 million
http://purl.obolibrary.org/obo/AfPO_0000149 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Central\|Northern\|Oti-Volta\|Western\|Northwest\|0.3 millions
http://purl.obolibrary.org/obo/AfPO_0000088 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|E\|5.3 millions
http://purl.obolibrary.org/obo/AfPO_0000437 | Niger–Congo, Bantu\|16 millions
http://purl.obolibrary.org/obo/AfPO_0000415 | 0.128 millions\|Afro-Asiatic\|Chadic\|Biu-Mandara\|B\|B.1
http://purl.obolibrary.org/obo/AfPO_0000103 | 6 millions\|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|S
http://purl.obolibrary.org/obo/AfPO_0000153 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|North\|Gur\|Central\|Northern\|Oti-Volta\|Western\|Northwest\|Dagaari-Birifor\|Dagaari\|1 million
http://purl.obolibrary.org/obo/AfPO_0000390 | Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|East\|Moru-Madi\|Central\|11 millions
http://purl.obolibrary.org/obo/AfPO_0000398 | Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|West\|Bongo-Bagirmi\|Bongo-Baka\|Baka\|Kacipo-Balesi\|Tennet\|Luo\|Lango-Acholi\|Pygmy
http://purl.obolibrary.org/obo/AfPO_0000398 | Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|West\|Bongo-Bagirmi\|Bongo-Baka\|Baka\|Kacipo-Balesi\|Tennet\|Luo\|Lango-Acholi\|0.25 million
http://purl.obolibrary.org/obo/AfPO_0000346 | Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|R\|0.3 million
http://purl.obolibrary.org/obo/AfPO_0000329 | 0.03 millions\|Indo-European
http://purl.obolibrary.org/obo/AfPO_0000426 | 0.5 million\|8.6 millions

Tasks related to it:

- [x] Figure out if the other information is using the incorrect annotation
- [x] Figure out what is the real population size in cases with 2 numbers
- [x] Make sure only one population size annotation for each term
- [ ] Add population size violation to QC #32

**Comment by anitacaron** [comment]
What are your thoughts on this @abenkahla @Melek-C @daniwelter?

**Comment by Melek-C** [comment]
One by one check can be a solution.

**Comment by anitacaron** [comment]
Thank you, @abenkahla. You should edit the file in `src/ontology/afpo-edit.ofn`. When you finish, please open a PR with the changes and tag this issue.

**Comment by abenkahla** [comment]
Dear @anitacaron ,

Edits were done, please check if there are still errors.
At least they should not be the same.

Many thanks,
Best,
Alia.

**Comment by anitacaron** [comment]
Thank you, @abenkahla! I saw your commit https://github.com/h3abionet/afpo/commit/cad268c730ce832a3d5a4eb7bb3d3a36d7728f4c, and everything looks fine. I'll run the query again.

**Comment by anitacaron** [comment]
@abenkahla, now there is a list of terms using `population:size` annotation for other information. Could you check, please?

entity | label | value
-- | -- | --
AfPO:0000242|Chipeta|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|N\|Chewa-Nyanja
AfPO:0000095|Anuak|Nilo-Saharan\|Satellite-Core\|Core\|Eastern Sudanic\|Southern\|Nilotic\|Western\|Luo\|Northern
AfPO:0000335|Banareng|Niger–Congo, Bantu
AfPO:0000375|Kwama|Nilo-Saharan
AfPO:0000135|Rendille|Afro-Asiatic\|Cushitic\|Lowland East\|Rendille–Boni\|Rendille
AfPO:0000337|Kwangali|Niger-Congo\|Atlantic-Congo\|Volta-Congo\|Benue-Congo\|Bantoid\|Southern\|Narrow Bantu\|Central\|K\|Luyana
AfPO:0000263|!Kung|Unclassified\|Kxʼa

**Comment by anitacaron** [comment]
In the commit https://github.com/h3abionet/afpo/commit/6b4779db2059567707e16cab5d420423fd19a637, the last issues were fixed.
