### ISSUE TITLE
Terms without text in label

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#23]
Should the label be Karonica and Kuria, @abenkahla? I can change it easily.

term|label
--|--
AfPO:0000580|<http://purl.obolibrary.org/obo/afpo.owl#Karonica>	
AfPO:0000579|<http://purl.obolibrary.org/obo/afpo.owl#Kuria>

**Comment by Melek-C** [comment]
fixed.

**Comment by anitacaron** [comment]
Thank you, @abenkahla and @Melek-C! I see that it was done in the commit https://github.com/h3abionet/afpo/commit/2e228aa522b712d9c7e406e613121fc5ce4c8269
