### ISSUE TITLE
Population group and country of origin inconsistency

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#25]
As discussed in our last meeting, here's the list of inconsistencies in population_group and country of origin.
For example, in Zambia, three populations (Bantu Central, British diaspora and Pygmy Central) define it as a country of origin, but they are not in Zambia as a population group.
The difference we saw in direct subclass and subclasses is that all subclasses of these three classes infer to have Zambia as the country of origin.

<img width="588" alt="Screenshot 2024-02-12 at 18 22 07" src="https://github.com/h3abionet/afpo/assets/2208124/29dda5b6-e2b6-47ab-9bb5-88f4c386ecef">

| population                                  | population_label | country                                                      | country_label                    |
|---------------------------------------------|------------------|--------------------------------------------------------------|----------------------------------|
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Algeria                          | Algeria                          |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Angola                           | Angola                           |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Angola                           | Angola                           |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Botswana                         | Botswana                         |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/Botswana                         | Botswana                         |
| http://purl.obolibrary.org/obo/AfPO_0000189 | Berber Western   | http://dbpedia.org/resource/Burkina_Faso                     | Burkina Faso                     |
| http://purl.obolibrary.org/obo/AfPO_0000151 | Gurma            | http://dbpedia.org/resource/Burkina_Faso                     | Burkina Faso                     |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Burundi                          | Burundi                          |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Burundi                          | Burundi                          |
| http://purl.obolibrary.org/obo/AfPO_0000283 | Baka_Cameroon    | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000278 | Kanuri           | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000058 | Tiv              | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000264 | Ubangi Central   | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Chad                             | Chad                             |
| http://purl.obolibrary.org/obo/AfPO_0000186 | Semite Central   | http://dbpedia.org/resource/Chad                             | Chad                             |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Comoros                          | Comoros                          |
| http://purl.obolibrary.org/obo/AfPO_0000203 | Akan             | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000443 | Kru              | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000207 | Banyarwanda      | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000264 | Ubangi Central   | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Egypt                            | Egypt                            |
| http://purl.obolibrary.org/obo/AfPO_0000358 | Nubian Northern  | http://dbpedia.org/resource/Egypt                            | Egypt                            |
| http://purl.obolibrary.org/obo/AfPO_0000385 | Beja             | http://dbpedia.org/resource/Eritrea                          | Eritrea                          |
| http://purl.obolibrary.org/obo/AfPO_0000113 | Oromo            | http://dbpedia.org/resource/Ethiopia                         | Ethiopia                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Gabon                            | Gabon                            |
| http://purl.obolibrary.org/obo/AfPO_0000203 | Akan             | http://dbpedia.org/resource/Ghana                            | Ghana                            |
| http://purl.obolibrary.org/obo/AfPO_0000151 | Gurma            | http://dbpedia.org/resource/Ghana                            | Ghana                            |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Guinea                           | Guinea                           |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000327 | British diaspora | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000199 | Kalenjin         | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000113 | Oromo            | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Lesotho                          | Lesotho                          |
| http://purl.obolibrary.org/obo/AfPO_0000443 | Kru              | http://dbpedia.org/resource/Liberia                          | Liberia                          |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Liberia                          | Liberia                          |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Libya                            | Libya                            |
| http://purl.obolibrary.org/obo/AfPO_0000307 | Toubou           | http://dbpedia.org/resource/Libya                            | Libya                            |
| http://purl.obolibrary.org/obo/AfPO_0000370 | Malagasy         | http://dbpedia.org/resource/Madagascar                       | Madagascar                       |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Malawi                           | Malawi                           |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Mali                             | Mali                             |
| http://purl.obolibrary.org/obo/AfPO_0000201 | Senufo           | http://dbpedia.org/resource/Mali                             | Mali                             |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Mauretania                       | Mauritania                       |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Morocco                          | Morocco                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Mozambique                       | Mozambique                       |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000331 | Khoekhoe         | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000200 | Pygmy Southern   | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Niger                            | Niger                            |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Nigeria                          | Nigeria                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Rwanda                           | Rwanda                           |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Rwanda                           | Rwanda                           |
| http://purl.obolibrary.org/obo/AfPO_0000205 | Jola             | http://dbpedia.org/resource/Senegal                          | Senegal                          |
| http://purl.obolibrary.org/obo/AfPO_0000428 | Wolof            | http://dbpedia.org/resource/Senegal                          | Senegal                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Somalia                          | Somalia                          |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000573 | Birwa            | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000331 | Khoekhoe         | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000305 | Baggara          | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000385 | Beja             | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000190 | Nubian Eastern   | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000395 | Sudanese Arab    | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000290 | Beti-Pahuin      | http://dbpedia.org/resource/São_Tomé_and_Príncipe            | São Tomé and Príncipe            |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Tanzania                         | Tanzania                         |
| http://purl.obolibrary.org/obo/AfPO_0000183 | Khoisan Eastern  | http://dbpedia.org/resource/Tanzania                         | Tanzania                         |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Tunisia                          | Tunisia                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000199 | Kalenjin         | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000198 | Luo              | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000327 | British diaspora | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |
| http://purl.obolibrary.org/obo/AfPO_0000350 | Ndebele          | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |
| http://purl.obolibrary.org/obo/AfPO_0000343 | Sotho            | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |

**Comment by Melek-C** [comment]
@anitacaron After discussing this issue with @abenkahla we found that in the previous version the terms belonging to "Rrelationship" annotation were modified as "subclass_of" and the "country_of_residence" was removed in the new version. Maybe something went wrong during the update or the data transfer from webprotégé to protégé. How we should process to fix this issue.

**Comment by Melek-C** [comment]
Reminder!

**Comment by anitacaron** [comment]
@Melek-C @abenkahla Sorry for the late reply on this. Do you still have the link to the ontology in the webprotege? Can I have access?

**Comment by Melek-C** [comment]
Hi @anitacaron @abenkahla just shared with you the access to the webprotege AfPO.

**Comment by anitacaron** [comment]
After meeting today, we decided: 
- [ ] Add population group in country
- [ ] Check the opposite direction
