### ISSUE TITLE
Duplicated definitions to disambiguate 

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#33]
Some of the definitions are the same when running the automated generation of definitions using the location and population size. What other information could we add to them to make unique definitions?

| Level | Rule Name            | Subject    | Property   | Value                                                               |
|-------|----------------------|------------|------------|---------------------------------------------------------------------|
| ERROR | duplicate_definition | Fon        | definition | A Western African population with a population size of 4 millions   |
| ERROR | duplicate_definition | Wolof      | definition | A Western African population with a population size of 4 millions   |
| ERROR | duplicate_definition | Ga-Adangbe | definition | A Western African population with a population size of 2 millions   |
| ERROR | duplicate_definition | Senufo     | definition | A Western African population with a population size of 2 millions   |
| ERROR | duplicate_definition | Urhobo     | definition | A Western African population with a population size of 2 millions   |
| ERROR | duplicate_definition | Dagaaba    | definition | A Western African population with a population size of 1 million    |
| ERROR | duplicate_definition | Guan       | definition | A Western African population with a population size of 1 million    |
| ERROR | duplicate_definition | Nuer       | definition | A Nilotic Eastern population with a population size of 3 millions   |
| ERROR | duplicate_definition | Kalenjin   | definition | A Nilotic Eastern population with a population size of 3 millions   |
| ERROR | duplicate_definition | Soninke    | definition | A Mande Western population with a population size of 2 millions     |
| ERROR | duplicate_definition | Mende      | definition | A Mande Western population with a population size of 2 millions     |
| ERROR | duplicate_definition | Kpelle     | definition | A Mande Western population with a population size of 2 millions     |
| ERROR | duplicate_definition | Tsimihety  | definition | A Malagasy population with a population size of 1.2 millions        |
| ERROR | duplicate_definition | Sakalava   | definition | A Malagasy population with a population size of 1.2 millions        |
| ERROR | duplicate_definition | Bilen      | definition | A Cushitic Eastern population with a population size of 0.2 million |
| ERROR | duplicate_definition | Saho       | definition | A Cushitic Eastern population with a population size of 0.2 million |
| ERROR | duplicate_definition | Himba      | definition | A Bantu Southern population with a population size of 0.05 million  |
| ERROR | duplicate_definition | Lemba      | definition | A Bantu Southern population with a population size of 0.05 million  |
| ERROR | duplicate_definition | Sena       | definition | A Bantu Eastern population with a population size of 2 millions     |
| ERROR | duplicate_definition | Chaga      | definition | A Bantu Eastern population with a population size of 2 millions     |
| ERROR | duplicate_definition | Luba       | definition | A Bantu Central population with a population size of >15 millions   |
| ERROR | duplicate_definition | Mongo      | definition | A Bantu Central population with a population size of >15 millions   |

**Comment by Melek-C** [comment]
We can modifiy these definitions manually to avoid dupliciation.
e.g The Fon are Western African population with a population size of 4 millions.
Is it feasable?

**Comment by anitacaron** [comment]
Great idea, I'll make the changes. Thanks!
