### ISSUE TITLE
Add description for the ontology

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#36]
There isn't a description of the ontology. Could you please write a sentence or two about the ontology?

**Comment by anitacaron** [comment]
I got this description from the OBO Foundry application (I changed the text a bit). Do you want to change anything, or can I use it as it is?

> AfPO is an ontology that enables annotating African individuals and combines knowledge accumulated about existing populations with their genetic fingerprints in a standardized format. The AfPO can be employed to classify African study participants comprehensively in prospective research studies. It can also be used to classify past study participants by mapping them using a language or ethnicity identifier or synonyms.

**Comment by Melek-C** [comment]
Looks goodfor me!
