### ISSUE TITLE
Replaced `dct:definition` by `IAO:0000115`

### ISSUE THREAD

**Issue by daniwelter** [h3abionet/afpo#4]
The OBO Foundry dashboard uses the annotation property `http://purl.obolibrary.org/obo/IAO_0000115` to identify textual definitions of classes. Using a different property will lead to a failure of the OBO dashboard for this indicator

**Comment by Melek-C** [comment]
Hi @daniwelter for the class definition we tried to use a common, formalized and normalized definitions. Should we review it?

**Comment by daniwelter** [comment]
@Melek-C I'm talking here specifically about the use of the annotation property `http://purl.org/dc/elements/1.1/description` to capture definitions.

**Comment by anitacaron** [comment]
It might be easier to change the annotation open the file in a text editor and using the find/replace to fix it.

**Comment by Melek-C** [comment]
Hi @anitacaron thanks for the advice, I think it's the best way to do it.

**Comment by anitacaron** [comment]
Keep aligned with Hancestro and do not use NCIT imports.
