### ISSUE TITLE
Split values in `language:synonym (AfPO:0000453)`

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#45]
Ideally, each annotation should have one value, especially for synonyms, where a user would search for one of the synonyms available. When there is more than one value in the annotation, the user must specify the whole list to get a result.

For example, in the population [Minianka](https://www.ebi.ac.uk/ols4/ontologies/afpo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FAfPO_0000121), it shows this list:

![Screenshot 2024-09-04 at 11 31 50](https://github.com/user-attachments/assets/045f8049-8ec3-4a0d-9d97-8b545c23550e)

**Comment by Melek-C** [comment]
HI @anitacaron you can fix this issue, thx!
