### ISSUE TITLE
Build textual definitions for most classes

### ISSUE THREAD

**Issue by daniwelter** [h3abionet/afpo#5]
The [6th OBO Foundry principle](https://obofoundry.org/principles/fp-006-textual-definitions.html) requires textual definitions for most of an ontology's classes. 

AfPO should make use of existing annotations to define a textual definition pattern for populations that can be built from the existing ontologies without the need to write additional definitions manually.

**Comment by anitacaron** [comment]
We can create a DOS-DP to help generate this.
