### ISSUE TITLE
Invalid value in `population:size` annotation

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#50]
I just found some more cases where the `population_size` is used for other purposes. Could you please check what the correct annotation should be?

class|class_label|population_size
-- | -- | --
AfPO:0000362 | Shilha | Afro-Asiatic\|Berber\|Northern\|Atlas
AfPO:0000204 | Daza | Nilo-Saharan
AfPO:0000198 | Luo | Nilo-Saharan, Luo, River-Lake
AfPO:0000241 | Bongo | Nilo-Saharan\|Satellite-Core\|Satellites\|Central Sudanic\|West\|Bongo-Bagirmi\|Bongo-Baka\|Bongo\|Kacipo-Balesi\|Tennet\|Luo\|Lango-Acholi

**Comment by anitacaron** [comment]
@Melek-C @abenkahla is family the correct annotation?

**Comment by Melek-C** [comment]
Hi @anitacaron, I should be family the correct annotation.
