### ISSUE TITLE
Modifying the content of the "family" property

### ISSUE THREAD

**Issue by abenkahla** [h3abionet/afpo#56]
Dear Anita,

When we asked Mariem Hannachi to prepare the African map, I noticed that the property "family" was modified and we somehow lost the "tree structure" of this property.

It took me some time to re-annotate them (I need it to write a script, correct my script, and look at the result and this takes me very long + holidays...) but I finally did it yesterday.

Attached is the family annotation. Could you please replace the current annotations with this one?

Please note that I used the ISO639-3 ID as a reference identifier instead of our identifier.

Please let me know if my request is not clear enough or if you need any additional information.
[afpo-full.iso639-3.family.txt](https://github.com/user-attachments/files/16674775/afpo-full.iso639-3.family.txt)

Thanks,
Best regards,
Alia.

**Comment by anitacaron** [comment]
I'm sorry for the issue caused when I split the family annotation. I'll add this back as soon as I return from my holiday on Sept 2.

**Comment by abenkahla** [comment]
No, it was not your fault, at least I don't think.
I think that it might have happened when I saved the ontology available on my computer on an ".owl" or an ".ofn" file.
Don't worry September 2 is very fine.
Enjoy.
Best,
Alia.
