### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by anitacaron** [h3abionet/afpo#8]
According to OBO Foundry Principle 1:

>OBO Foundry Ontologies MUST EITHER be released under a [Creative Commons Attribution 3.0 Unported (CC BY 3.0)](https://creativecommons.org/licenses/by/3.0/) license or later (e.g. [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/), OR released into the public domain under [Creative Commons CC0 1.0 Public Domain Dedication (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/).

https://obofoundry.org/principles/fp-001-open.html#recommendations-and-requirements

**Comment by anitacaron** [comment]
Which license should be added, @Melek-C @abenkahla @daniwelter?

**Comment by daniwelter** [comment]
I would go with CC BY 4.0
